package com.proctoring.domain;

public enum EventType {
    FACE_NOT_DETECTED,
    FACE_NOT_CENTERED,
    MULTIPLE_FACES,
    PHONE_DETECTED,
    TAB_SWITCH,
    NOISE_DETECTED,
    SCREEN_SHARE_STOPPED,
    FULLSCREEN_EXIT,
    FULLSCREEN_RETURNED,
    EXTENSION_CONNECTED,
    EXTENSION_DISCONNECTED,
    MICROPHONE_DISABLED,
    CAMERA_DISABLED,
    EXAM_FAILED_PHONE,
    SCREENSHOT_ATTEMPT,
    COPY_ATTEMPT,
    TEST_SUBMITTED,
    MANUAL_NOTE
}
